kind: pipeline
type: docker
name: Docker - Nginx FPM Proxy

steps:
  - name: Publish Main Image
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PAT
      repo: hercdottech/docker-nginx-fpm-proxy
      tags:
        - "v1.0.${DRONE_BUILD_NUMBER}"
        - "latest"
    when:
      branch:
        - main

  - name: Publish Dev Image
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PAT
      repo: hercdottech/docker-nginx-fpm-proxy
      tags:
        - "v1.0.${DRONE_BUILD_NUMBER}-dev"
    when:
      branch:
        exclude:
          - main
