kind: pipeline
type: docker
name: Docker - Nginx FPM Proxy

steps:
  - name: Publish Main Image
    image: thegeeklab/drone-docker-buildx:24.1.3
    privileged: true
    settings:
      username:
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PAT
      repo: hercdottech/docker-nginx-fpm-proxy
      tags:
        - "v1.0.${DRONE_BUILD_NUMBER}"
        - "latest"
      platforms:
        - linux/amd64
        - linux/arm64
    when:
      branch:
        - main

  - name: Publish Dev Image
    image: thegeeklab/drone-docker-buildx:24.1.3
    privileged: true
    settings:
      username:
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PAT
      repo: hercdottech/docker-nginx-fpm-proxy
      tags:
        - "v1.0.${DRONE_BUILD_NUMBER}-dev"
      platforms:
        - linux/amd64
        - linux/arm64
    when:
      branch:
        exclude:
          - main
